version: 0.2
# Buildspec Reference Doc: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec-ref-syntax

#################################
# Runtime Environment Variables #
#################################

env:
  variables:
    artifact-s3bucket: "rashmi-ohio-sam-demo"
     $remote = "s3://${AWS::AccountId}-${AWS::Region}-artifacts/"
    ${Account_Name}-${Xoriant_ENV_Name}-app
    key: "value"
  parameter-store:
    key: "value"
    key: "value"
phases:
  install:
    commands:
    # - |
    #     pip install -U pip
    #     pip install -U awscli
    # - pip3 install aws-sam-cli


  pre_build:
    commands:
      - echo "[Pre-Build phase]"

  build:
    commands:
      # - sam build 
      - aws cloudformation package --template-file template.yaml --s3-bucket ${AccountName}-${Region}-artifacts --output-template-file packaged.yaml
      - aws s3 cp ./packaged.yaml s3://rashmi-ohio-sam-demo/packaged.yaml
      - aws s3 cp s3://rashmi-ohio-sam-demo/packaged.yaml C:\codebuild\tmp\output
      
      # - copy packaged.yaml C:\codebuild\tmp\output
      # - aws s3 cp ./packaged.yaml C:\codebuild\tmp\output\
      # - aws s3 cp s3://rashmi-ohio-sam-demo/packaged.yaml C:\codebuild\tmp\output
      # - aws s3 cp s3://rashmi-ohio-sam-demo/packaged.yaml C:\codebuild\tmp\output\
      # - aws s3 cp ./packaged.yaml .
      # - sam deploy --stack-name codebuildtesting --change-set-type=CREATE

  post_build:
    commands:
      - aws cloudformation deploy --template-file C:\codebuild\tmp\output\packaged.yaml --capabilities CAPABILITY_IAM --stack-name testcvdg
     
artifacts:
  type: zip
  files:
    - packaged.yaml