version: 0.2

phases:
  install:
    commands:
    # - |
    #     pip install -U pip
    #     pip install -U awscli
    #     pip3 install aws-sam-cli


  pre_build:
    commands:
      - echo "[Pre-Build phase]"

  build:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket rashmi-ohio-sam-demo --output-template-file packaged.yaml --stack-name teststack1234


  post_build:
    commands:
      # - sam package --output-template-file packaged.yaml --s3-bucket rashmi478-sam-demo

artifacts:
  type: zip
  files:
    - packaged.yaml