version: 0.2

phases:
  install:
    commands:
    # - |
    #     pip install -U pip
    #     pip install -U awscli
    # - pip3 install aws-sam-cli


  pre_build:
    commands:
      - echo "[Pre-Build phase]"

  build:
    commands:
      # - sam build 
      - aws cloudformation package --template-file template.yaml --s3-bucket rashmi-ohio-sam-demo --output-template-file packaged.yaml
      - aws s3 cp ./packaged.yaml s3://rashmi-ohio-sam-demo/packaged.yaml
      - aws s3 cp s3://rashmi-ohio-sam-demo/packaged.yaml C:\codebuild\tmp\output
      - aws cloudformation deploy --template-file C:\codebuild\tmp\output\packaged.yaml --stack-name testcvdg
      # - copy packaged.yaml C:\codebuild\tmp\output
      # - aws s3 cp ./packaged.yaml C:\codebuild\tmp\output\
      # - aws s3 cp s3://rashmi-ohio-sam-demo/packaged.yaml C:\codebuild\tmp\output
      # - aws s3 cp s3://rashmi-ohio-sam-demo/packaged.yaml C:\codebuild\tmp\output\
      # - aws s3 cp ./packaged.yaml .
      # - sam deploy --stack-name codebuildtesting --change-set-type=CREATE

  post_build:
    commands:
      # - sam package --output-template-file packaged.yaml --s3-bucket rashmi478-sam-demo
      # aws cloudformation deploy --template-file s3://rashmi-ohio-sam-demo/packaged.yaml --stack-name testcvdg
       - 
artifacts:
  type: zip
  files:
    - packaged.yaml