version: 0.2

phases:
  install:
    commands:
    # - |
    #     pip install -U pip
    #     pip install -U awscli
    # - pip3 install aws-sam-cli


  pre_build:
    commands:
      # - echo "[Pre-Build phase]
         
  build:
    commands:
      # - sam build 
      - aws cloudformation package --template-file master.yaml --s3-bucket rashmi-ohio-sam-demo --output-template-file packaged.yaml
      - echo %CODEBUILD_SRC_DIR%
      - aws s3 cp ./packaged.yaml s3://rashmi-ohio-sam-demo/packaged.yaml
      - aws s3 cp s3://rashmi-ohio-sam-demo/packaged.yaml C:\codebuild\tmp\output
      - echo CODE BUILD SRC DIRECTORY
      - echo %CODEBUILD_SRC_DIR%
    #  finally:
    #   - echo THE PATH WORK IS !!!
    #   - echo CODE BUILD SRC DIRECTORY
    #   - echo %CODEBUILD_SRC_DIR%
      # - copy packaged.yaml C:\codebuild\tmp\output
      # - aws s3 cp ./packaged.yaml C:\codebuild\tmp\output\
      # - aws s3 cp s3://rashmi-ohio-sam-demo/packaged.yaml C:\codebuild\tmp\output
      # - aws s3 cp s3://rashmi-ohio-sam-demo/packaged.yaml C:\codebuild\tmp\output\
      # - aws s3 cp ./packaged.yaml .
      # - sam deploy --stack-name codebuildtesting --change-set-type=CREATE

  post_build:
    commands:
      # - aws cloudformation deploy --template-file C:\codebuild\tmp\output\packaged.yaml --capabilities CAPABILITY_IAM --stack-name codebuildstack --parameter-overrides apiGatewayStageName=qa lambdaFunctionName=MeghFlow-function12
      # - aws cloudformation deploy --template-file $CODEBUILD_SRC_DIR\packaged.yaml --capabilities CAPABILITY_IAM --stack-name $accountname$region --parameter-overrides apiGatewayStageName=qa lambdaFunctionName=MeghFlow-function12
      - aws cloudformation deploy --template-file C:\codebuild\tmp\output\packaged.yaml --region us-east-2 --stack-name InitialSetup --capabilities CAPABILITY_IAM  --parameter-overrides S3BucketName=rashmi-ohio-sam-demo S3KeyName=MeghFlow-DBConnMgmt-Lambda-DBConnMgmtFunction.zip HandlerName=com.xoriant.meghflow.dbconnmgmt.lambda.DBConnMgmtLambda::handleRequest apiGatewayStageName=dev AccountName=barclays Region=us-east-2 PrimePartitionKey=ConnectionId PrimePartitionKeyType=S ReadCapacityUnits=5 WriteCapacityUnits=5
      # - aws cloudformation deploy --template-file C:\codebuild\tmp\output\packaged.yaml --capabilities CAPABILITY_IAM --stack-name codebuildstack --parameters https://your-bucket-name.s3.amazonaws.com/params/parameters.json
      # - aws cloudformation deploy --template-file C:\codebuild\tmp\output\packaged.yaml --capabilities CAPABILITY_IAM --stack-name codebuildstack --parameters-overrides $(cat parameters-dev.properties)
artifacts:
  type: zip
  files:
    - packaged.yaml