version: 0.2

phases:
  install:
    runtime-versions:
      java: 8

  pre_build:
    commands:
      - echo "[Pre-Build phase]"

  build:
    commands:
      - sam build

  post_build:
    commands:
      - sam package --output-template-file packaged.yaml --s3-bucket rashmi478-sam-demo

artifacts:
  type: zip
  files:
    - packaged.yaml